/* ============================================================
 * js/posts.js — AUTO-GENERATED by tools/build_posts.py
 * 请勿手改！新增/修改文章后运行: py tools/build_posts.py
 * 所有页面统计（文章数/标签/字数/阅读时长）以此文件为准
 * ============================================================ */
window.POSTS = [
  {"id": "post14", "title": "Agent集群工程：从RAFT隐喻到全栈开发协作模式", "date": "2026-07-22", "tag": "Agent集群", "tags": ["Agent集群"], "excerpt": "关于 Agent 集群工程，实际上它是一套在短时间内搭出来的、相对规范完整的 Agent 协作模式。核心目标不是让单个 Agent 多强，而是让多个 Agent 能稳定地一起完成一件复杂的事。", "words": 1452, "readMinutes": 5, "headings": 7, "type": "post", "duplicateOf": null},
  {"id": "post9", "title": "从Vibe Coding到Agent工作流：40天没写代码，产出却超过去一年半", "date": "2026-05-19", "tag": "Agent工作流", "tags": ["Agent工作流"], "excerpt": "很久没更新了。虽然也没人看，但是还是总结一下做了什么。", "words": 1722, "readMinutes": 6, "headings": 7, "type": "post", "duplicateOf": "post13"},
  {"id": "post13", "title": "从Vibe Coding到Agent工作流：40天没写代码，产出却超过去一年半", "date": "2026-05-19", "tag": "Agent工作流", "tags": ["Agent工作流"], "excerpt": "很久没更新了。虽然也没人看，但是还是总结一下做了什么。", "words": 1722, "readMinutes": 6, "headings": 7, "type": "post", "duplicateOf": null},
  {"id": "post12", "title": "我花了两周，给 Django 做了一款“零侵入”的缓存外挂", "date": "2026-04-30", "tag": "开源项目", "tags": ["开源项目"], "excerpt": "Redis 这个词，我听过很久了。但一直觉得“那是大厂才用的东西”。", "words": 880, "readMinutes": 3, "headings": 5, "type": "post", "duplicateOf": null},
  {"id": "post8", "title": "日志：后端开发的另一只眼", "date": "2026-04-01", "tag": "后端规范", "tags": ["后端规范"], "excerpt": "在上一次的哈希存储文章里，代码块中藏着这么一行：", "words": 1772, "readMinutes": 6, "headings": 7, "type": "post", "duplicateOf": null},
  {"id": "post7", "title": "哈希？数据泄露的最后一道防线？", "date": "2026-03-31", "tag": "后端安全", "tags": ["后端安全"], "excerpt": "当我们开始接触后端开发，不可避免要面对用户的敏感数据存储——密码、账户余额、API密钥……恶意渗透攻击下， 数据库暴露是很难完全避免的 。所以我们不仅要从前端到数据库调用层层设防，对于数据本身，也要做好被窃取的准备。", "words": 990, "readMinutes": 4, "headings": 6, "type": "post", "duplicateOf": null},
  {"id": "post6", "title": "关于 BuGroup ，关于我们", "date": "2026-03-29", "tag": "BuGroup", "tags": ["BuGroup"], "excerpt": "BuGroup 是由我和 Witherwithwinter 创办的。说是“创办”，实际上还没有具体组织。名字来源于 Witherwithwinter 大一时的 IDEA，说实话我们也不知道未来这个名字会走到哪一步。但好歹也是慢慢在做了，尽管…", "words": 842, "readMinutes": 3, "headings": 2, "type": "post", "duplicateOf": null},
  {"id": "post5", "title": "开发接单 · 一个普通人的真实经历", "date": "2026-03-26", "tag": "接单经验", "tags": ["接单经验"], "excerpt": "说实话，我自己从开始接单到现在，也才一个来月。一共成了三个单子，遇到不少要么甲方跑路，要么就是要求脱离了我的能力范畴，比如美术设计要达标啥的，甚至有外包出来预算2w做个硬件+前后端产品的。", "words": 976, "readMinutes": 3, "headings": 6, "type": "post", "duplicateOf": null},
  {"id": "post4", "title": "你想活出怎么样的人生", "date": "2026-03-25", "tag": "个人成长", "tags": ["个人成长"], "excerpt": "算起来，算法竞赛算是我接触的方向里面，最难走也最不喜欢的了。我的水平顶了天也就CF 1100-1200分左右，C++的熟练度也一般。能蹭上一次比赛，说到底确实是巧合。", "words": 880, "readMinutes": 3, "headings": 4, "type": "post", "duplicateOf": null},
  {"id": "post3", "title": "VibeCoding · 个人开发者的AI时代生存指南", "date": "2026-03-25", "tag": "个人开发", "tags": ["个人开发"], "excerpt": "AI编码最大的区别在于——它彻底改变了开发的效率和门槛。一个好的idea，现在可以迅速被实现。但这里有一个关键的分水岭：你需要区分“开发”和“简单的Ctrl+C/V”。", "words": 883, "readMinutes": 3, "headings": 5, "type": "post", "duplicateOf": null},
  {"id": "post2", "title": "算法竞赛入门 · ACMer 起步指南", "date": "2026-03-23", "tag": "算法竞赛", "tags": ["算法竞赛"], "excerpt": "很多刚接触算法竞赛的同学都会问： “我是零基础，怎么开始？” 这篇文章写给准备入坑 ACM/ICPC、蓝桥杯、CSP 等算法竞赛的萌新，帮你理清思路，少走弯路。", "words": 765, "readMinutes": 3, "headings": 6, "type": "post", "duplicateOf": null},
  {"id": "post1", "title": "Django Vue AdminX 框架开发实战", "date": "2026-03-22", "tag": "Django", "tags": ["Django"], "excerpt": "一套完整的企业级后台管理系统框架，基于 Django 5.2 和 Vue 3 开发。", "words": 194, "readMinutes": 1, "headings": 2, "type": "post", "duplicateOf": null},
  {"id": "3d", "title": "眼球追随效果", "date": "", "tag": "", "tags": [], "excerpt": "", "words": 0, "readMinutes": 0, "headings": 0, "type": "page", "duplicateOf": null}
];
