/* ============================================================
 * ram-blog site engine
 *
 * Single runtime entry for lists, stats, filters, archive, friends,
 * article metadata, footer and small navigation behavior.
 * Data source: window.POSTS generated by tools/build.mjs.
 * ============================================================ */
(function () {
    'use strict';

    var POSTS = Array.isArray(window.POSTS) ? window.POSTS : [];
    var FRIENDS = Array.isArray(window.FRIENDS) ? window.FRIENDS : [];
    var state = {
        q: '',
        tag: '',
        sort: 'newest'
    };

    function $(sel, root) {
        return (root || document).querySelector(sel);
    }

    function $all(sel, root) {
        return Array.prototype.slice.call((root || document).querySelectorAll(sel));
    }

    function esc(value) {
        return String(value == null ? '' : value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    function formatNumber(n) {
        return Number(n || 0).toLocaleString('zh-CN');
    }

    function articles() {
        return POSTS.filter(function (p) {
            return p.type === 'post' && !p.duplicateOf && p.date;
        }).sort(function (a, b) {
            return a.date < b.date ? 1 : -1;
        });
    }

    function allTags() {
        var seen = {};
        articles().forEach(function (post) {
            (post.tags || []).concat(post.tag || []).forEach(function (tag) {
                if (tag) seen[tag] = true;
            });
        });
        return Object.keys(seen).sort(function (a, b) {
            return a.localeCompare(b, 'zh-CN');
        });
    }

    function totalWords(list) {
        return (list || articles()).reduce(function (sum, p) {
            return sum + (p.words || 0);
        }, 0);
    }

    function totalMinutes(list) {
        return (list || articles()).reduce(function (sum, p) {
            return sum + (p.readMinutes || 0);
        }, 0);
    }

    function tagFrequency() {
        var freq = {};
        articles().forEach(function (post) {
            (post.tags || []).forEach(function (tag) {
                if (tag) freq[tag] = (freq[tag] || 0) + 1;
            });
            if (post.tag) freq[post.tag] = Math.max(freq[post.tag] || 0, 1);
        });
        return freq;
    }

    function activeYears(list) {
        var source = list || articles();
        if (!source.length) return 0;
        var years = source.map(function (p) {
            return parseInt(p.date.slice(0, 4), 10);
        });
        return Math.max.apply(null, years) - Math.min.apply(null, years) + 1;
    }

    function readQuery() {
        var params = new URLSearchParams(window.location.search);
        state.q = (params.get('q') || '').trim();
        state.tag = (params.get('tag') || '').trim();
        state.sort = params.get('sort') || state.sort;
    }

    function writeQuery() {
        var params = new URLSearchParams();
        if (state.q) params.set('q', state.q);
        if (state.tag) params.set('tag', state.tag);
        if (state.sort && state.sort !== 'newest') params.set('sort', state.sort);
        var next = window.location.pathname + (params.toString() ? '?' + params.toString() : '');
        window.history.replaceState(null, '', next);
    }

    function matchesFilters(post) {
        var haystack = [
            post.title,
            post.excerpt,
            post.tag,
            (post.tags || []).join(' ')
        ].join(' ').toLowerCase();
        var q = state.q.toLowerCase();
        var tags = (post.tags || []).concat(post.tag || []);
        return (!q || haystack.indexOf(q) >= 0) && (!state.tag || tags.indexOf(state.tag) >= 0);
    }

    function filteredArticles() {
        var list = articles().filter(matchesFilters);
        if (state.sort === 'oldest') {
            list.reverse();
        } else if (state.sort === 'longest') {
            list.sort(function (a, b) {
                return (b.readMinutes || 0) - (a.readMinutes || 0) || b.words - a.words;
            });
        } else if (state.sort === 'shortest') {
            list.sort(function (a, b) {
                return (a.readMinutes || 0) - (b.readMinutes || 0) || a.words - b.words;
            });
        }
        return list;
    }

    function postHref(post) {
        var inPosts = window.location.pathname.replace(/\\/g, '/').indexOf('/posts/') >= 0;
        return (inPosts ? '' : 'posts/') + encodeURIComponent(post.id) + '.html';
    }

    function renderMetricStrip() {
        var strip = $('#siteMetrics');
        if (!strip) return;
        var list = articles();
        strip.innerHTML = [
            ['文章', list.length + ' 篇'],
            ['标签', allTags().length + ' 个'],
            ['字数', formatNumber(totalWords(list))],
            ['阅读', totalMinutes(list) + ' 分钟']
        ].map(function (item) {
            return '<div class="metric"><span>' + esc(item[0]) + '</span><strong>' + esc(item[1]) + '</strong></div>';
        }).join('');
    }

    function fillTagSelects() {
        $all('[data-tag-select]').forEach(function (select) {
            var value = select.value || state.tag;
            select.innerHTML = '<option value="">全部标签</option>' + allTags().map(function (tag) {
                return '<option value="' + esc(tag) + '">' + esc(tag) + '</option>';
            }).join('');
            select.value = value;
        });
    }

    function syncControls() {
        $all('[data-post-search]').forEach(function (input) {
            if (input.value !== state.q) input.value = state.q;
        });
        $all('[data-tag-select]').forEach(function (select) {
            if (select.value !== state.tag) select.value = state.tag;
        });
        $all('[data-sort-select]').forEach(function (select) {
            if (select.value !== state.sort) select.value = state.sort;
        });
    }

    function bindControls() {
        $all('[data-post-search]').forEach(function (input) {
            input.addEventListener('input', function () {
                state.q = input.value.trim();
                writeQuery();
                renderDynamic();
            });
        });
        $all('[data-tag-select]').forEach(function (select) {
            select.addEventListener('change', function () {
                state.tag = select.value;
                writeQuery();
                renderDynamic();
            });
        });
        $all('[data-sort-select]').forEach(function (select) {
            select.addEventListener('change', function () {
                state.sort = select.value || 'newest';
                writeQuery();
                renderDynamic();
            });
        });
        $all('[data-clear-filters]').forEach(function (button) {
            button.addEventListener('click', function () {
                state.q = '';
                state.tag = '';
                state.sort = 'newest';
                writeQuery();
                renderDynamic();
            });
        });
    }

    function renderFilterStatus(count) {
        $all('[data-filter-status]').forEach(function (el) {
            var parts = [];
            if (state.q) parts.push('关键词「' + esc(state.q) + '」');
            if (state.tag) parts.push('标签「' + esc(state.tag) + '」');
            el.innerHTML = parts.length
                ? '已筛选：' + parts.join(' / ') + '，命中 <strong>' + count + '</strong> 篇'
                : '当前显示全部 <strong>' + count + '</strong> 篇文章';
        });
    }

    function renderHomeList() {
        var container = $('#homePage');
        if (!container) return;
        var list = filteredArticles();
        renderFilterStatus(list.length);
        if (!list.length) {
            container.innerHTML = '<div class="empty-state">没有匹配的文章，换个关键词或清空筛选。</div>';
            return;
        }
        container.innerHTML = list.map(function (post) {
            var tags = (post.tags && post.tags.length ? post.tags : [post.tag]).filter(Boolean);
            return '' +
                '<article class="post-card">' +
                    '<div class="post-card-top">' +
                        '<a class="post-tag" href="archive.html?tag=' + encodeURIComponent(post.tag || '') + '"># ' + esc(post.tag || '未分类') + '</a>' +
                        '<span class="post-date">' + esc(post.date) + '</span>' +
                    '</div>' +
                    '<h2 class="post-title"><a href="' + postHref(post) + '">' + esc(post.title) + '</a></h2>' +
                    (post.excerpt ? '<p class="post-excerpt">' + esc(post.excerpt) + '</p>' : '') +
                    '<div class="post-footer">' +
                        '<span>' + post.readMinutes + ' 分钟 · ' + formatNumber(post.words) + ' 字</span>' +
                        '<a href="' + postHref(post) + '">阅读全文</a>' +
                    '</div>' +
                    (tags.length ? '<div class="post-tags">' + tags.map(function (tag) {
                        return '<a class="tag" href="archive.html?tag=' + encodeURIComponent(tag) + '">#' + esc(tag) + '</a>';
                    }).join('') + '</div>' : '') +
                '</article>';
        }).join('');
    }

    function renderArchive() {
        var container = $('#archiveContent');
        if (!container) return;
        var list = filteredArticles();
        renderFilterStatus(list.length);
        if (!list.length) {
            container.innerHTML = '<div class="archive-list"><div class="empty-state">没有匹配的归档记录。</div></div>';
            return;
        }
        var grouped = {};
        list.forEach(function (post) {
            var year = post.date.slice(0, 4);
            var month = post.date.slice(5, 7);
            grouped[year] = grouped[year] || {};
            grouped[year][month] = grouped[year][month] || [];
            grouped[year][month].push(post);
        });
        var html = '<div class="archive-list">';
        Object.keys(grouped).sort().reverse().forEach(function (year) {
            html += '<section class="archive-year-block"><h2 class="archive-year">' + year + ' 年</h2>';
            Object.keys(grouped[year]).sort().reverse().forEach(function (month) {
                html += '<div class="archive-month">' +
                    '<div class="archive-month-title">' + parseInt(month, 10) + ' 月' +
                    '<span class="archive-month-count">' + grouped[year][month].length + ' 篇</span></div>' +
                    '<ul class="archive-items">';
                grouped[year][month].forEach(function (post) {
                    html += '<li><a href="posts/' + encodeURIComponent(post.id) + '.html">' + esc(post.title) + '</a>' +
                        '<span class="archive-date">' + esc(post.date) + ' · ' + post.readMinutes + ' 分钟 · ' + formatNumber(post.words) + ' 字</span></li>';
                });
                html += '</ul></div>';
            });
            html += '</section>';
        });
        html += '</div>';
        container.innerHTML = html;
    }

    function renderStats() {
        var list = articles();
        var stats = [
            { label: '文章总数', value: list.length + ' 篇' },
            { label: '标签数量', value: allTags().length + ' 个' },
            { label: '累计阅读', value: totalMinutes(list) + ' 分钟' },
            { label: '总字数', value: formatNumber(totalWords(list)) },
            { label: '友情链接', value: FRIENDS.length + ' 个' },
            { label: '覆盖年份', value: activeYears(list) + ' 年' }
        ];
        $all('.stats-list').forEach(function (ul) {
            ul.innerHTML = stats.map(function (item) {
                return '<li><span>' + esc(item.label) + '</span><span class="stat-value">' + esc(item.value) + '</span></li>';
            }).join('');
        });
    }

    function renderTagCloud() {
        var freq = tagFrequency();
        var entries = Object.keys(freq).sort(function (a, b) {
            return freq[b] - freq[a] || a.localeCompare(b, 'zh-CN');
        }).slice(0, 12);
        $all('.tag-cloud').forEach(function (cloud) {
            if (!entries.length) {
                cloud.innerHTML = '';
                return;
            }
            var max = freq[entries[0]];
            cloud.innerHTML = entries.map(function (tag) {
                var size = 0.86 + 0.18 * (freq[tag] / max);
                var active = state.tag === tag ? ' is-active' : '';
                return '<a class="tag' + active + '" style="font-size:' + size.toFixed(2) + 'rem" href="archive.html?tag=' +
                    encodeURIComponent(tag) + '" title="' + freq[tag] + ' 篇">#' + esc(tag) + '</a>';
            }).join('');
        });
    }

    function renderRecentPosts() {
        $all('[data-recent-posts]').forEach(function (box) {
            box.innerHTML = articles().slice(0, 5).map(function (post) {
                return '<a class="mini-link" href="' + (box.dataset.recentPosts === 'root' ? 'posts/' : '../posts/') +
                    encodeURIComponent(post.id) + '.html"><span>' + esc(post.title) + '</span><small>' +
                    esc(post.date) + '</small></a>';
            }).join('');
        });
    }

    function renderFriends() {
        var container = $('#friendsGrid');
        if (!container) return;
        if (!FRIENDS.length) {
            container.innerHTML = '<div class="empty-state">暂无友链。</div>';
            return;
        }
        container.innerHTML = FRIENDS.map(function (friend) {
            var fallback = '<div class="friend-fallback">' + esc((friend.name || '?').charAt(0)) + '</div>';
            var avatar = friend.avatar
                ? '<img src="' + esc(friend.avatar) + '" alt="' + esc(friend.name) + '" loading="lazy" onerror="this.replaceWith(this.nextElementSibling)">' + fallback
                : fallback;
            return '' +
                '<a href="' + esc(friend.url) + '" target="_blank" class="friend-card" rel="noopener noreferrer">' +
                    '<div class="friend-avatar">' + avatar + '</div>' +
                    '<div class="friend-info">' +
                        '<h3 class="friend-name">' + esc(friend.name) + '</h3>' +
                        '<p class="friend-desc">' + esc(friend.desc || '') + '</p>' +
                        '<div class="friend-tags">' + (friend.tags || []).map(function (tag) {
                            return '<span class="friend-tag">#' + esc(tag) + '</span>';
                        }).join('') + '</div>' +
                    '</div>' +
                '</a>';
        }).join('');
    }

    function renderPostMeta() {
        var meta = $('#postMeta');
        if (!meta) return;
        var idMatch = /([^/]+)\.html$/.exec(location.pathname);
        var id = idMatch ? idMatch[1] : '';
        var post = POSTS.filter(function (p) { return p.id === id; })[0];
        if (!post) return;
        meta.textContent = post.date + ' · 约 ' + post.readMinutes + ' 分钟阅读 · ' + formatNumber(post.words) + ' 字';
    }

    function renderFooter() {
        $all('.site-footer').forEach(function (footer) {
            var year = new Date().getFullYear();
            footer.innerHTML = '<p>© 2024-' + year + ' RaM\'s Blog · ' +
                articles().length + ' 篇文章 · 数据由构建脚本自动生成</p>';
        });
    }

    function setActiveNav() {
        var path = window.location.pathname.replace(/\\/g, '/');
        var current = path.split('/').pop() || 'index.html';
        if (path.indexOf('/posts/') >= 0) current = 'index.html';
        $all('.nav-links a').forEach(function (link) {
            var href = link.getAttribute('href') || '';
            var file = href.split('/').pop();
            if (file === current) link.setAttribute('aria-current', 'page');
        });
    }

    function bindNavToggle() {
        var toggle = $('.nav-toggle');
        var links = $('.nav-links');
        if (!toggle || !links) return;
        toggle.addEventListener('click', function () {
            var open = links.classList.toggle('is-open');
            toggle.setAttribute('aria-expanded', String(open));
        });
    }

    function renderDynamic() {
        syncControls();
        renderHomeList();
        renderArchive();
        renderTagCloud();
    }

    function init() {
        readQuery();
        fillTagSelects();
        bindControls();
        bindNavToggle();
        setActiveNav();
        renderMetricStrip();
        renderStats();
        renderRecentPosts();
        renderFriends();
        renderPostMeta();
        renderFooter();
        renderDynamic();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
